inherit_from: .rubocop_todo.yml

Style/ConditionalAssignment:
  Enabled: false

Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/FileName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false
  
Style/StringLiterals:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Max: 30

ClassLength:
  Max: 250

MethodLength:
  Max: 250

AllCops:
  TargetRubyVersion: '2.4.2'
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/migrate/*'
    - 'test/**/*'
    - 'vendor/bundle/**/*'
    - 'bundle/**/*'
    - 'config/**/*'
    - 'bin/*'